### ISSUE TITLE
Improve discoverability of your work on HF

### ISSUE THREAD

**Issue by NielsRogge** [xiaobiaodu/DreamCar#1]
Hi,

Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2407.16988 (feel free to claim the paper so that it appears at your HF account!).

However there are a couple of things which could improve the discoverability of your work, which I've listed below.

## Upload and link models to the paper page

I see the models are currently on Google Drive, which hurts their discoverability. Would be awesome to push them to the hub so that people find them when filtering on "image-to-3D": https://huggingface.co/models?pipeline_tag=image-to-3d&sort=trending

Here's a guide: https://huggingface.co/docs/hub/models-uploading. Make sure to add `pipeline_tag: image-to-3d` as metadata to the model card so that people find them. There's a guide [here](https://huggingface.co/docs/huggingface_hub/en/guides/model-cards#update-metadata).

It would be great to link the models to the paper, see here on how to do that: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper

Let me know if you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by xiaobiaodu** [comment]
Thanks for your good suggestion. We've uploaded our checkpoint in huggingface https://huggingface.co/xiaobiaodu/dreamcar123/tree/main

**Comment by NielsRogge** [comment]
Hi,

Thanks for doing that. I'm curious, where did you find about uploading a model? Cause ideally one could leverage this guide: https://huggingface.co/docs/hub/models-uploading#upload-a-pytorch-model-using-huggingfacehub in case your model is a custom PyTorch one.

Also, would it be possible to add a minimal model card (README)?

**Comment by xiaobiaodu** [comment]
Done. I upload the checkpoint by the web interaction UI.

**Comment by NielsRogge** [comment]
Great, feel free to link to it from the main README of this Github repo :)
