### ISSUE TITLE
inference code 

### ISSUE THREAD

**Issue by Daniellli** [xiaobiaodu/DreamCar#3]
Hi, thank you for your contribution.
I try to reproduce the qualitative results in your paper. But, after going through your code, I did not find related inference code.
Could you provide an inference code for beginners to quick start, including the use of your pretrained model.
Best Regards,
Daniel.

**Comment by xiaobiaodu** [comment]
Hi


Did you try the commands in readme?





------------------ Original ------------------
From: Shaocong Xu ***@***.***&gt;
Date: Wed, Sep 4, 2024 11:48 PM
To: xiaobiaodu/DreamCar ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [xiaobiaodu/DreamCar] inference code  (Issue #3)





 
Hi, thank you for your contribution.
 I try to reproduce the qualitative results in your paper. But, after going through your code, I did not find related inference code.
 Could you provide an inference code for beginners to quick start, including the use of your pretrained model.
 Best Regards,
 Daniel.

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by Daniellli** [comment]
yes and I went through the code  and readme again, there are only training codes, not inference code.

**Comment by xiaobiaodu** [comment]
It looks like you lack of the knowledge about 3D generation. You could read some basic papers then try our code.





------------------ Original ------------------
From: Shaocong Xu ***@***.***&gt;
Date: Thu, Sep 5, 2024 0:16 AM
To: xiaobiaodu/DreamCar ***@***.***&gt;
Cc: Xiaobiao Du ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xiaobiaodu/DreamCar] inference code  (Issue #3)





 
yes and I went through the code  and readme again, there are only training codes, not inference code.

**Comment by Daniellli** [comment]
yes, I am a beginner as mentioned  above.   
Ok,  thank you for your patience.
Best regards,
Daniel

**Comment by Daniellli** [comment]
Hi, I have reproduced results in your paper.  It is very  promising.  
Now, I want to try more examples. Could you provide  the script to extract the example sequence from nuscenes  such as `example_data/94b33ce331b844dcb991a2020742cebf` you provided.
best regards,
Daniel

**Comment by xiaobiaodu** [comment]
Hi

Thanks for your recognition of our work. I've uploaded the code about Nuscenes processing. Please check it.
